### PR TITLE
Update auth endpoints, don't force new-user for bad rdstoken path.

### LINKED ISSUE #82: drop_auth
Relevant URLs
```
/R/drop_auth.R: authorize = "https://www.dropbox.com/1/oauth2/authorize",
/R/drop_auth.R: access = "https://api.dropbox.com/1/oauth2/token"
```
Need to update auth to v2. 

Other notes:
- Perhaps print a message to the user that they add httr oauth files to their gitignore.

Notes from @scheidec

- Code: https://github.com/karthik/rdrop2/blob/master/R/drop_auth.R
- Change from v1: /1/oauth2/authorize to v2: /oath2/authorize
- V1 docs: https://www.dropbox.com/developers-v1/core/docs#oa2-authorize
- V2 docs: https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize
- Only the path has changed, fixed in PR #75

access = "https://api.dropbox.com/1/oauth2/token"

- Code: https://github.com/karthik/rdrop2/blob/master/R/drop_auth.R
- Change from v1: /1/oauth2/token to v2: /oauth2/authorize
- V1 docs: https://www.dropbox.com/developers-v1/core/docs#oa2-token
- V2 docs: https://www.dropbox.com/developers/documentation/http/documentation#oauth2-token
- Only the path has changed, fixed in PR #75

### PR DESCRIPTION
**Pull request by ClaytonJY**
Also cleaned up code and docs.

Closes #82.

### CODE REVIEW

**Comment by ClaytonJY** [comment]
@karthik chose not to add message about `.httr_oauth` > `.gitignore`, since we can't be sure they don't already have that, and it's handled by `httr`, not us, and is subject to change.

The code around `rdstoken` was really odd in that if you accidentally passed it a bad path, it would assume you wanted a new-user and would delete a `.httr-oauth` if present before re-authing interactively. Especially since we explicitly say to use `rdstoken` in remote environments, this is bad behaviour as it'll mean minor bugs cause server hangs. Went ahead and changed it, though I could pull that out.

Also added a trivial test; hard to fail it but serves as a placeholder for more testing down the line (though these should also be split into multiple test files).

May have gone a little overboard on reformatting, but I think it's an improvement; would be happy to revert or edit further.

**Comment by ClaytonJY** [comment]
Tests pass, but `R CMD Check` does not and likely will not on travis; see #94.

**Comment by ClaytonJY** [comment]
rebased against `master`.

**Comment by karthik** [comment]
LGTM

**Pull request merged**
