### PR TITLE
Clean up on tests

### PR DESCRIPTION
**Pull request by karthik**
- Removed the httr options at the top
- Check to see that there is no `.httr-oauth` in the `tests/testthat` folder. We can include instructions for future contributors (in contributors.md) to save a `token.rds` in their  copy (but it is git ignored so wont show up on the repo) for local testing.
- Removed the file deletions at the end (It was originally meant to clean out my test Dropbox account but as we saw, it can create issues when someone is doing this on their production account. Each test removes files it creates at the end of that context and we should make sure of that before approving new tests).
- Added `*.rds` to gitignore instead of token in case anyone uses a different name for their file. Should I just leave it as `token.rds` since that is the name of the file being read into the tests?
- I also merged in your PR (https://github.com/karthik/rdrop2/pull/97) so once you review and merge this, we can close that one.

### CODE REVIEW

**Comment by ClaytonJY** [comment]
@karthik
- good to remove that option
- not sure what this test helps with; having an `.httr-oauth` around doesn't hurt in any way, we've got it in the top-level `.gitignore` so it's hard to accidentally commit one, and the auth test will fail if they don't have their token properly configured
- definitely best to remove the "delete everything" statement at the end, but it reveals that proper cleanup is NOT occurring; when I run tests from this branch after manually emptying my dropbox account, I'm left with 2 `csv`'s and `duck_rabbit.gif`. I think this should be fixed before we merge this in.
- I'm ambivalent on `token.rds` vs `*.rds`; if someone has some other token name, tests will fail, but i suppose it might prevent an accidental commit (e.g. `git add -a`), so why not
- would it make more sense to merge mine and then rebase this one onto master? auto issue closing, etc.

**Comment by karthik** [comment]
>  not sure what this test helps with; having an .httr-oauth around doesn't hurt in any way, we've got it in the top-level .gitignore so it's hard to accidentally commit one, and the auth test will fail if they don't have their token properly configured

ok, makes sense.

> definitely best to remove the "delete everything" statement at the end, but it reveals that proper cleanup is NOT occurring; when I run tests from this branch after manually emptying my dropbox account, I'm left with 2 csv's and duck_rabbit.gif. I think this should be fixed before we merge this in.

I will fix these and push more commits.

> would it make more sense to merge mine and then rebase this one onto master? auto issue closing, etc.

Sounds good, doing that now.

**Comment by karthik** [comment]
@ClaytonJY Tests are cleaned up now and should no longer leave stray csvs or gifs.

**Comment by karthik** [comment]
Note that I removed Appveyor temporarily, since it does not decrypt tokens. We need to address that separately but for now it wont show a few tests failing.

**Pull request merged**
