### PR TITLE
dont try to print NULL directory listing; issue #31 (NOT TESTED)

### PR DESCRIPTION
**Pull request by daattali**
I just edited this file in the browser, I haven't tested it

### CODE REVIEW

**Comment by karthik** [comment]
Thanks @daattali 
Instead of returning `NULL`, which causes problems with the print method, I also realized it would cause problems combining data unless someone explicitly filters out the `NULL`. Instead, I now return an empty `data.frame`

e.g.

```r
> drop_create("nfolder")
Folder nfolder created successfully

> drop_dir("nfolder")
data frame with 0 columns and 0 rows
> drop_dir()
Source: local data frame [1 x 5]

      path is_dir    root bytes                        modified
1 /nfolder   TRUE dropbox     0 Tue, 09 Jun 2015 11:36:57 +0000
```

This is in the branch [dir_null](https://github.com/karthik/rdrop2/tree/dir_null) which I'll merge shortly after adding a test for it. Does this behavior seem ok to you?

**Comment by karthik** [comment]
If my fix is ok, I'll close this PR out.

**Comment by daattali** [comment]
Yes yours is definitely a better solution, thanks

**Comment by karthik** [comment]
cool. thanks @daattali

**Pull request closed without merging**
